"""empty message

Revision ID: 20051ea3e094
Revises: 5209b347a70e
Create Date: 2019-09-25 08:00:41.401564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20051ea3e094'
down_revision = '5209b347a70e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('genres', sa.String(length=120), nullable=True))
    op.alter_column('Venue', 'seeking_talent',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('Venue', 'genre')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('genre', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.alter_column('Venue', 'seeking_talent',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('Venue', 'genres')
    # ### end Alembic commands ###
