"""empty message

Revision ID: 534558effd0c
Revises: b44f3d28b89c
Create Date: 2019-09-18 07:43:49.778535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '534558effd0c'
down_revision = 'b44f3d28b89c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('venue_id', sa.Integer(), nullable=False))
    op.alter_column('Show', 'artist_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'Show', 'Venue', ['venue_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Show', type_='foreignkey')
    op.alter_column('Show', 'artist_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('Show', 'venue_id')
    # ### end Alembic commands ###
